eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8769
spring:
  application:
    name: zuul-service

zuul:
  routes:
    api-a:
      path: /api-member/**
      service-id: member-service
    api-b:
      path: /api-order/**
      service-id: order-service
